version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx   
    container_name: nginx 
    ports:
      - 8888:80
    environment:
      SERVICE_PORTS: "80" 
      WORKER_PROCESSES: "2"
      WORKER_CONNECTIONS: "1024"
      KEEPALIVE_TIMEOUT: "65"
      GZIP: "on"
      BACKEND_HOST: app:3000
      BACKEND_MAX_FAILS: "3"
      BACKEND_FAIL_TIMEOUT: "10s"
      SERVER_PORT: "80"
      SERVER_NAME: "todo_app_nginx"
      LOG_STDOUT: "true"

  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    image: app                 
    container_name: app 
    ports:         
      - 3000:3000
    volumes:
      - ./myapp:/src
    command: [sh, -c, npm install && npm start]